# Sistemas de ecuaciones segun matrices

## Imports

In [1]:
import numpy as np
np.set_printoptions(suppress=True)
%matplotlib inline

1. Primero debemos crear nuestra matriz la cual presenta n filas y m columnas
2. Ademas devemos generar el vector que supuestamente seria la solucion de este problema

In [18]:
#                  1,2,3,4,5,6,7,8,9,10
z=8.63187
i=0.006
matriz =np.array([[1,0,0,0,0,1],
                  [0,2,0,0,0,0],
                  [2,1,0,2,2,1],
                  [0,0,2,0,0,0],
                  [0,0,0,1,0,0],
                  [i,0,i,i,i,i-1]])
vector_sol=np.array([5.25,6.48,0.521+2*z,0.051+2*z*3.76,0.0304,0])

In [19]:
print(matriz)

[[ 1.     0.     0.     0.     0.     1.   ]
 [ 0.     2.     0.     0.     0.     0.   ]
 [ 2.     1.     0.     2.     2.     1.   ]
 [ 0.     0.     2.     0.     0.     0.   ]
 [ 0.     0.     0.     1.     0.     0.   ]
 [ 0.006  0.     0.006  0.006  0.006 -0.994]]


In [20]:
sol=np.linalg.solve(matriz,vector_sol)
print(np.around(sol,3))


[ 5.011  3.24  32.481  0.03   2.112  0.239]


## Producto punto entre 2 vectores

In [5]:
v2=[44,18,28,64,32,28]
print(np.dot(sol,v2))

1264.4859136000002


## otra matriz

In [15]:

z=11.3
f=0.003
#                  1,2,3,4,5,Z
matriz =np.array([[1,0,0,0,1],
                  [0,2,0,0,0],
                  [2,1,0,2,1],
                  [0,0,2,0,0],
                  [f,0,f,f,f-1]])
vector_sol=np.array([6.83,12.2,0.13+2*z,0.06+z*2*3.76,0])

In [16]:
print(matriz)

[[ 1.     0.     0.     0.     1.   ]
 [ 0.     2.     0.     0.     0.   ]
 [ 2.     1.     0.     2.     1.   ]
 [ 0.     0.     2.     0.     0.   ]
 [ 0.003  0.     0.003  0.003 -0.997]]


In [17]:
sol=np.linalg.solve(matriz,vector_sol)
print(np.around(sol,5))


[ 6.67727  6.1     42.518    1.56136  0.15273]


In [18]:
v2=[44,18,28,64,28]
print(np.dot(sol,v2))

1698.3076494742113


###  Otra matriz

In [2]:

f=0.001 #CO
g=0.15  #O_2
#                  1,2,3,4,5,Z
matriz =np.array([[1,0,0,1,0,0],
                  [0,2,0,0,0,0],
                  [2,1,0,1,2,-2],
                  [0,0,2,0,0,-2*3.76],
                  [f,0,f,f-1,f,0],
                  [g,0,g,g,g-1,0]])
vector_sol=np.array([80*12+20*19,80*24+20*35,20*2,0,0,0])
print(matriz)

[[ 1.     0.     0.     1.     0.     0.   ]
 [ 0.     2.     0.     0.     0.     0.   ]
 [ 2.     1.     0.     1.     2.    -2.   ]
 [ 0.     0.     2.     0.     0.    -7.52 ]
 [ 0.001  0.     0.001 -0.999  0.001  0.   ]
 [ 0.15   0.     0.15   0.15  -0.85   0.   ]]


In [3]:
sol=np.linalg.solve(matriz,vector_sol)
print(np.around(sol,5))


[ 1309.54981  1310.      24542.65944    30.45019  4567.52814  6527.30304]


In [94]:
sol=np.array(sol[0:len(sol)-1])
print(sol)
np.dot(sol,np.array([44,18,28,28,32]))


[ 1309.54981242  1310.         24542.65944143    30.45018758
  4567.52813672]


915408.1617340555

In [5]:
k1=80*2/19340
k2=20*2/19340
Z=1975*92/271128
f=0.001 #CO
g=0.15  #O_2
#                  1,2,3,4,5,Z
matriz =np.array([[1,0,0,1,0],
                  [0,2,0,0,0],
                  [0,0,2,0,0],
                  [f,0,f,f-1,f],
                  [g,0,g,g,g-1]])
vector_sol=np.array([k1*12+k2*19,k1*24+k2*35,2*3.76*Z,0,0])
print(matriz)



[[ 1.     0.     0.     1.     0.   ]
 [ 0.     2.     0.     0.     0.   ]
 [ 0.     0.     2.     0.     0.   ]
 [ 0.001  0.     0.001 -0.999  0.001]
 [ 0.15   0.     0.15   0.15  -0.85 ]]


In [6]:
sol=np.linalg.solve(matriz,vector_sol)
print(np.around(sol,5))


[0.13545 0.13547 2.51981 0.00313 0.46913]
