# Sistemas de ecuaciones segun matrices

## Imports

In [17]:
import numpy as np
np.set_printoptions(suppress=True)
%matplotlib inline

1. Primero debemos crear nuestra matriz la cual presenta n filas y m columnas
2. Ademas devemos generar el vector que supuestamente seria la solucion de este problema

In [18]:
#                  1,2,3,4,5,6,7,8,9,10
z=8.63187
i=0.006
matriz =np.array([[1,0,0,0,0,1],
                  [0,2,0,0,0,0],
                  [2,1,0,2,2,1],
                  [0,0,2,0,0,0],
                  [0,0,0,1,0,0],
                  [i,0,i,i,i,i-1]])
vector_sol=np.array([5.25,6.48,0.521+2*z,0.051+2*z*3.76,0.0304,0])

In [19]:
print(matriz)

[[ 1.     0.     0.     0.     0.     1.   ]
 [ 0.     2.     0.     0.     0.     0.   ]
 [ 2.     1.     0.     2.     2.     1.   ]
 [ 0.     0.     2.     0.     0.     0.   ]
 [ 0.     0.     0.     1.     0.     0.   ]
 [ 0.006  0.     0.006  0.006  0.006 -0.994]]


In [20]:
sol=np.linalg.solve(matriz,vector_sol)
print(np.around(sol,3))


[ 5.011  3.24  32.481  0.03   2.112  0.239]


## Producto punto entre 2 vectores

In [5]:
v2=[44,18,28,64,32,28]
print(np.dot(sol,v2))

1264.4859136000002


## otra matriz

In [24]:

ze=5.775462963
f=0.083
g=0.007
#                  1,2,3,4,5,6,Z
matriz =np.array([[1,0,0,0,0,1,0],
                  [0,2,0,0,0,0,0],
                  [2,1,0,2,2,1,-2],
                  [0,0,2,0,0,0,-2*3.76],
                  [0,0,0,1,0,0,0],
                  [f,0,f,f,f-1,f,0],
                  [g,0,g,g,g,g-1,0]])
vector_sol=np.array([5.0380,4.9000,1.0250,0.0786,0.0250,0,0])

In [25]:
print(matriz)

[[ 1.     0.     0.     0.     0.     1.     0.   ]
 [ 0.     2.     0.     0.     0.     0.     0.   ]
 [ 2.     1.     0.     2.     2.     1.    -2.   ]
 [ 0.     0.     2.     0.     0.     0.    -7.52 ]
 [ 0.     0.     0.     1.     0.     0.     0.   ]
 [ 0.083  0.     0.083  0.083 -0.917  0.083  0.   ]
 [ 0.007  0.     0.007  0.007  0.007 -0.993  0.   ]]


In [26]:
sol=np.linalg.solve(matriz,vector_sol)
print(np.around(sol,5))


[ 4.73427  2.45    34.72517  0.025    3.60133  0.30373  9.22496]
